### ISSUE TITLE
How to add plain text, conf, cfg and yml to highlight list?

### ISSUE THREAD

**Issue by danieru-desu** [ObserverOfTime/coloresque.vim#1]
Hi. The name is pretty much self-explanatory. Is there a way to do that? I mean, this doesn't work:
let g:coloresque_extra_filetypes = ['plain','cfg','conf','yml']

**Comment by ObserverOfTime** [comment]
https://github.com/ObserverOfTime/coloresque.vim#commands
> #### `ColoresqueAddFiletype`
>
> Takes a filetype as an argument and adds support for it.
> To enable it, add it to `g:coloresque_extra_filetypes`.

**Comment by NightH4nter** [comment]
![image](https://user-images.githubusercontent.com/31319604/78020629-d8d44280-7362-11ea-8829-927a80c8a651.png)

**Comment by danieru-desu** [comment]
I did `ColoresqueAddFiletype yml` but nothing changed. Putting `yaml` instead of `yml` (even though the filetype is .yml) doesn't help as well.

**Comment by ObserverOfTime** [comment]
The extension is not the filetype. The filetype is named `yaml`.

**Comment by danieru-desu** [comment]
Okay, I had a typo in `.vimrc`. Two more questions: 
1. What is filetype name for plain text files? 
2. Should I request a feature here or make another issue?

**Comment by ObserverOfTime** [comment]
> What is filetype name for plain text files?

It's `text`. You can see the filetype when you open a file.
Also, `ColoresqueAddFiletype` will autocomplete filetypes.

> Should I request a feature here or make another issue?

I'm no longer maintaining this repo. Feel free to fork it if you want to add a feature.

**Comment by danieru-desu** [comment]
> It's text. You can see the filetype when you open a file.


It doesn't work with `text`. 
I have a Polybar config, which I assume is a plain text file since it doesn't have an extention. And i have this line in `.vimrc`:
`let g:coloresque_extra_filetypes = ['yaml','text']`
Is it me doing something wrong?

**Comment by ObserverOfTime** [comment]
You can get the filetype with `:set filetype?` or `:echo &filetype`.

**Comment by danieru-desu** [comment]
The first one returns `filetype=` and the second returns nothing.

**Comment by danieru-desu** [comment]
Putting a space into single quotes inside .vimrc does nothing. Neither does putting `plaintext` there.

**Comment by ObserverOfTime** [comment]
> The first one returns filetype= and the second returns nothing.

That means it has no filetype. You have to set it yourself.
I cannot help you any further than that. Read the Vim docs.
