### ISSUE TITLE
Fix for vimrc

### ISSUE THREAD

**Issue by BSDxxxx** [ObserverOfTime/coloresque.vim#2]
![image](https://user-images.githubusercontent.com/59258592/79060897-df48af80-7cbc-11ea-9211-81ba875b713f.png)
![image](https://user-images.githubusercontent.com/59258592/79060918-099a6d00-7cbd-11ea-875b-d7b3fe904484.png)

**Comment by ObserverOfTime** [comment]
I'm not maintaining this plugin anymore. I recommend using something else.

**Comment by BSDxxxx** [comment]
@ObserverOfTime Tks, [vim-coloresque](https://github.com/gko/vim-coloresque) would do.
